const products=[
{id:1,name:"Satin Slip Dress",category:"Women",sub:"Dresses & Gowns",price:3499,old:4499,color:"Pink",sizes:["XS","S","M","L"],rating:4.9,img:"https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=700&q=80",desc:"A fluid satin silhouette with delicate straps and a flattering bias cut. Designed for effortless evenings."},
{id:2,name:"Classic Oxford Shirt",category:"Men",sub:"Shirts & T-Shirts",price:2199,old:2799,color:"White",sizes:["S","M","L","XL"],rating:4.8,img:"https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=700&q=80",desc:"Crisp cotton tailoring meets a relaxed contemporary fit. A wardrobe essential for workdays and weekends."},
{id:3,name:"Relaxed Straight Jeans",category:"Women",sub:"Jeans & Skirts",price:2999,color:"Blue",sizes:["XS","S","M","L","XL"],rating:4.7,img:"https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=80",desc:"High-rise straight-leg denim with a soft vintage wash and comfortable stretch."},
{id:4,name:"Leather Chelsea Boots",category:"Men",sub:"Footwear",price:4599,color:"Brown",sizes:["S","M","L"],rating:4.9,img:"https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=700&q=80",desc:"Polished leather Chelsea boots with a durable sole and timeless profile."},
{id:5,name:"Minimal Blazer",category:"Women",sub:"Tops & Blouses",price:3999,color:"Beige",sizes:["XS","S","M","L"],rating:4.8,img:"https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=700&q=80",desc:"A softly structured blazer designed to elevate everyday dressing."},
{id:6,name:"Everyday Oversized Tee",category:"Men",sub:"Shirts & T-Shirts",price:1299,color:"Black",sizes:["S","M","L","XL"],rating:4.6,img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=80",desc:"Heavyweight cotton jersey with an easy oversized fit and clean finish."},
{id:7,name:"Mini City Bag",category:"Women",sub:"Accessories",price:2699,color:"Black",sizes:["XS"],rating:4.8,img:"https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80",desc:"A compact structured bag made for your daily essentials."},
{id:8,name:"Kids Weekend Set",category:"Kids",sub:"Boys Clothing",price:1799,color:"Blue",sizes:["6-8Y","8-10Y","10-12Y"],rating:4.7,img:"https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=700&q=80",desc:"A soft cotton co-ord made for playground adventures and relaxed weekends."},
{id:9,name:"Tailored Trousers",category:"Men",sub:"Jeans & Trousers",price:2499,color:"Beige",sizes:["S","M","L","XL"],rating:4.7,img:"https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=700&q=80",desc:"Clean tailored trousers with a modern tapered leg."},
{id:10,name:"Floral Midi Dress",category:"Women",sub:"Dresses & Gowns",price:3299,color:"Pink",sizes:["XS","S","M","L"],rating:4.9,img:"https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=80",desc:"A romantic floral midi with a softly defined waist and flowing skirt."},
{id:11,name:"Kids Knit Cardigan",category:"Kids",sub:"Girls Clothing",price:1599,color:"Pink",sizes:["6-8Y","8-10Y","10-12Y"],rating:4.6,img:"https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=700&q=80",desc:"A cozy knit layer in a playful silhouette."},
{id:12,name:"Suede Crossbody",category:"Men",sub:"Accessories",price:2399,color:"Brown",sizes:["S"],rating:4.8,img:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80",desc:"Compact suede crossbody with understated hardware and adjustable strap."}
];
let cart=JSON.parse(localStorage.getItem("stylehub-cart")||"[]"), wishlist=JSON.parse(localStorage.getItem("stylehub-wishlist")||"[]"), discount=0;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const money=n=>"₹"+Math.round(n).toLocaleString("en-IN");
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function save(){localStorage.setItem("stylehub-cart",JSON.stringify(cart));localStorage.setItem("stylehub-wishlist",JSON.stringify(wishlist));renderCart();updateCount()}
function updateCount(){$("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function filtered(){
 let a=[...products],c=$("#categoryFilter").value,s=$("#sizeFilter").value,col=$("#colorFilter").value,q=($("#productSearch").value||"").toLowerCase(),sort=$("#sortFilter").value;
 if(c!=="All")a=a.filter(p=>p.category===c);if(s!=="All")a=a.filter(p=>p.sizes.includes(s));if(col!=="All")a=a.filter(p=>p.color===col);if(q)a=a.filter(p=>(p.name+" "+p.sub+" "+p.category).toLowerCase().includes(q));
 if(sort==="low")a.sort((x,y)=>x.price-y.price);if(sort==="high")a.sort((x,y)=>y.price-x.price);if(sort==="rating")a.sort((x,y)=>y.rating-x.rating);return a
}
function renderProducts(){const grid=$("#productGrid");const a=filtered();grid.innerHTML=a.length?a.map((p,i)=>`<article class="product-card"><button class="heart ${wishlist.includes(p.id)?"active":""}" data-wish="${p.id}">${wishlist.includes(p.id)?"♥":"♡"}</button>${i<2?'<span class="badge">NEW</span>':""}<div class="product-image" data-product="${p.id}"><img loading="lazy" src="${p.img}" alt="${p.name}"></div><div class="product-info" data-product="${p.id}"><h3>${p.name}</h3><div class="meta">${p.category} · ${p.color} <span class="stars">★ ${p.rating}</span></div><div class="price">${money(p.price)}</div></div></article>`).join(""):`<p>No products match your filters.</p>`}
function openDrawer(id){$("#overlay").classList.add("open");$(id).classList.add("open")}
function closeAll(){$("#overlay").classList.remove("open");$$(".drawer,.modal").forEach(x=>x.classList.remove("open"))}
function renderCart(){const box=$("#cartItems");if(!cart.length){box.innerHTML='<div style="padding:45px 25px;text-align:center;color:#888">Your bag is empty.<br><br><a class="text-btn" href="#shop">Continue shopping →</a></div>';$("#cartSubtotal").textContent=money(0);return}box.innerHTML=cart.map(x=>`<div class="cart-item"><img src="${x.img}" alt="${x.name}"><div><h4>${x.name}</h4><small>${x.size} · ${x.color}</small><div class="qty"><button data-qty="${x.key}" data-d="-1">−</button><span>${x.qty}</span><button data-qty="${x.key}" data-d="1">+</button></div></div><div><strong>${money(x.price*x.qty)}</strong><button class="remove" data-remove="${x.key}">remove</button></div></div>`).join("");let total=cart.reduce((a,x)=>a+x.price*x.qty,0);$("#cartSubtotal").textContent=money(total)}
function openProduct(id){const p=products.find(x=>x.id==id);let size=p.sizes[0];$("#productDetail").innerHTML=`<div class="product-detail"><img class="detail-image" src="${p.img}" alt="${p.name}"><div class="detail-info"><p class="eyebrow">${p.category} / ${p.sub}</p><h2>${p.name}</h2><div class="detail-price">${money(p.price)}</div><p class="detail-desc">${p.desc}</p><div class="variant-title">SIZE</div><div class="variants" id="sizes">${p.sizes.map((s,i)=>`<button class="variant ${i===0?"selected":""}" data-size="${s}">${s}</button>`).join("")}</div><div class="variant-title">COLOR · ${p.color}</div><div class="variants"><button class="swatch selected" style="background:${p.color.toLowerCase()}"></button></div><button class="btn btn-dark full" id="addDetail" style="margin-top:28px">ADD TO BAG · ${money(p.price)}</button><p style="font-size:10px;color:#999;margin-top:18px">Free shipping over ₹2,999 · 7-day easy returns</p></div></div>`;$("#productModal").classList.add("open");$("#overlay").classList.add("open");$$("[data-size]").forEach(b=>b.onclick=()=>{$$("[data-size]").forEach(z=>z.classList.remove("selected"));b.classList.add("selected");size=b.dataset.size});$("#addDetail").onclick=()=>addToCart(p,size)}
function addToCart(p,size=p.sizes[0]){const key=p.id+"-"+size;const item=cart.find(x=>x.key===key);if(item)item.qty++;else cart.push({key,id:p.id,name:p.name,price:p.price,img:p.img,size,color:p.color,qty:1});save();toast(p.name+" added to your bag");closeAll();openDrawer("#cartDrawer")}
document.addEventListener("click",e=>{
 const prod=e.target.closest("[data-product]");if(prod)openProduct(prod.dataset.product);
 const wish=e.target.closest("[data-wish]");if(wish){let id=+wish.dataset.wish;wishlist.includes(id)?wishlist=wishlist.filter(x=>x!==id):wishlist.push(id);save();renderProducts();toast(wishlist.includes(id)?"Added to wishlist":"Removed from wishlist")}
 const q=e.target.closest("[data-qty]");if(q){let x=cart.find(x=>x.key===q.dataset.qty);x.qty+=+q.dataset.d;if(x.qty<=0)cart=cart.filter(y=>y.key!==x.key);save()}
 const r=e.target.closest("[data-remove]");if(r){cart=cart.filter(x=>x.key!==r.dataset.remove);save()}
 if(e.target.matches("[data-close]"))closeAll()
});
["categoryFilter","sizeFilter","colorFilter","sortFilter"].forEach(id=>$("#"+id).addEventListener("change",renderProducts));
$("#productSearch").addEventListener("input",renderProducts);$("#clearFilters").onclick=()=>{$("#categoryFilter").value="All";$("#sizeFilter").value="All";$("#colorFilter").value="All";$("#sortFilter").value="featured";$("#productSearch").value="";renderProducts()};
$$(".category-card").forEach(b=>b.onclick=()=>{$("#categoryFilter").value=b.dataset.category;renderProducts();$("#shop").scrollIntoView()});
$("#cartBtn").onclick=()=>openDrawer("#cartDrawer");$("#accountBtn").onclick=()=>openDrawer("#accountDrawer");$("#overlay").onclick=closeAll;
$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");$$(".nav a").forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
$("#searchToggle").onclick=()=>{$("#searchBar").classList.toggle("open");if($("#searchBar").classList.contains("open"))$("#searchInput").focus()};$("#searchClose").onclick=()=>$("#searchBar").classList.remove("open");$("#searchInput").oninput=()=>{$("#productSearch").value=$("#searchInput").value;renderProducts();$("#shop").scrollIntoView()};
$("#checkoutBtn").onclick=()=>{if(!cart.length)return toast("Your bag is empty");closeAll();$("#checkoutTotal").textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0)*(1-discount));$("#checkoutModal").classList.add("open")};
$("#applyCoupon").onclick=()=>{if($("#couponInput").value.trim().toUpperCase()==="STYLE20"){discount=.2;toast("20% discount applied");$("#checkoutTotal").textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0)*.8)}else toast("Invalid coupon code")};
$("#copyCoupon").onclick=()=>{navigator.clipboard?.writeText("STYLE20");toast("Coupon STYLE20 copied")};
$("#newsletterForm").onsubmit=e=>{e.preventDefault();toast("Welcome to the StyleHub club!");e.target.reset()};
$("#contactForm").onsubmit=e=>{e.preventDefault();toast("Thanks! We'll get back to you soon.");e.target.reset()};
$("#authForm").onsubmit=e=>{e.preventDefault();toast("Account action completed (demo)");e.target.reset()};
$$("[data-tab]").forEach(b=>b.onclick=()=>{$$("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#authName").style.display=b.dataset.tab==="register"?"block":"none"});
$("#authName").style.display="none";
$("#checkoutForm").onsubmit=e=>{e.preventDefault();const order="SH"+Date.now().toString().slice(-6);cart=[];discount=0;save();closeAll();toast("Order "+order+" placed successfully!");};
renderProducts();renderCart();updateCount();
